backend:
  name: github
  repo: TheSovaDigital/sovazone
  branch: main
  base_url: https://sovazone.vercel.app
  auth_endpoint: api/auth

media_folder: "image/blog"
public_folder: "/image/blog"

publish_mode: editorial_workflow

collections:
 - name: "blog"
    label: "Блог"
    folder: "content/blog"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"

    fields:
      - { label: "Заголовок", name: "title", widget: "string" }

      - {
          label: "Слуг",
          name: "slug",
          widget: "string",
          required: true,
          hint: "Только латиница, цифры и дефисы. Например: instagram-updates-2026"
        }

      - {
          label: "Дата",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD",
          time_format: false
        }

      - {
          label: "Короткое описание",
          name: "description",
          widget: "text",
          required: false
        }

      - {
          label: "Обложка",
          name: "cover",
          widget: "image",
          required: false
        }

      - {
          label: "Категория",
          name: "category",
          widget: "select",
          options: ["Статьи", "Новости", "Кейсы"],
          default: "Статьи"
        }

      - {
          label: "Текст публикации",
          name: "body",
          widget: "markdown"
        }
